# Official Node JS 18.16.1 bullseye Docker image
FROM node:18.16.1-bullseye

# Set work directory
WORKDIR /usr/src/app

VOLUME ["/usr/src/app"]
#RUN npm install -g nodemon && npm install path fs express express-session cors bindings dotenv child_process